# -*- coding: utf-8 -*-
"""Phase 2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1snP1kvxjB3j4D6bZCAujoieUTmq_mR8N
"""

# Simple Rule-Based Customer Support Chatbot

# Predefined Q&A
faq = {
    "hi": "Hello! How can I help you today?",
    "hello": "Hi there! What can I do for you?",
    "what is your name": "I'm your virtual assistant.",
    "how to reset password": "To reset your password, go to settings and select 'Reset Password'.",
    "how to contact support": "You can reach us at support@example.com.",
    "bye": "Thank you for chatting with us. Goodbye!"
}

def chatbot_response(user_input):
    user_input = user_input.lower().strip()
    # Try to find a direct match
    if user_input in faq:
        return faq[user_input]
    else:
        return "Sorry, I don't understand that. Please try rephrasing."

# Simulate chatbot in Google Colab using input() won't work.
# So we simulate a short conversation using a list.

# Sample user inputs
user_inputs = [
    "hi",
    "what is your name",
    "how to reset password",
    "bye"
]

# Display chatbot responses
print("Customer Support Chatbot\n")
for user_input in user_inputs:
    print("You:", user_input)
    print("Bot:", chatbot_response(user_input))
    print("---")
